---
- name: Apply sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: true
    sysctl_file: /etc/sysctl.d/99-harden.conf
  loop: "{{ harden.sysctl.parameters }}"
  loop_control:
    label: "{{ item.name }}"
