---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
    enabled: true

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true

- name: Restart auditd
  ansible.builtin.command: service auditd restart
  changed_when: true

- name: Load audit rules
  ansible.builtin.command: augenrules --load
  changed_when: false
